remote_theme: jekyll/minima 
plugins:
  - jekyll-feed
  - jekyll-remote-theme
google_analytics: G-W33X68MWKZ
minima:
  skin: solarized-dark
  social_links:
    - { platform: github,         url: "https://github.com/cboler", icon: github }
    - { platform: linkedin,       url: "https://www.linkedin.com/in/christopher-boler-816422139", icon: linkedin }
    - { platform: stackoverflow,  url: "https://stackoverflow.com/users/359317/cboler", icon: stack-overflow }

exclude:
  - 404.md
  - README.md
header_pages:
  - about.md
  - resume.md
description: >
 Computer Scientist, Software Developer, Learner
 Please don't copy or reuse anything in _posts without permission and attribution.
 Everything else is under the MIT License: https://opensource.org/license/mit

author:
  email: christopher.boler@gmail.com
  name: Christopher Boler
