theme: minima
google_analytics: G-W33X68MWKZ
minima:
  skin: dark
  social_links:
    github: cboler
    linkedin: christopher-boler-816422139
    stackoverflow: cboler
exclude:
  - 404.md
  - README.md
  
title: Chris Boler
description: >
  Computer Scientist,
  Software Developer, 
  Learner
email: christopher.boler@gmail.com
author:
  name: Chris Boler
  email: "christopher.boler@gmail.com"
