remote_theme: jekyll/minima 
plugins:
  - jekyll-feed
  - jekyll-remote-theme
google_analytics: G-W33X68MWKZ
minima:
  skin: dark
  social_links:
    - { platform: github,         url: "https://github.com/cboler", icon: github }
    - { platform: linkedin,       url: "https://www.linkedin.com/in/christopher-boler-816422139", icon: linkedin }
    - { platform: stackoverflow,  url: "https://stackoverflow.com/users/359317/cboler", icon: stack-overflow }

exclude:
  - 404.md
  - README.md
header_pages:
  - about.md
  - resume.md
title: Chris Boler
description: Computer Scientist, Software Developer, Learner
email: christopher.boler@gmail.com
author: Christopher Boler
